### ISSUE TITLE
Dockerfile does not build

### ISSUE THREAD

**Issue by davidroberson** [PankratzLab/NGS-PCA#8]
This part fails - Step 11/13 : COPY --from=1 /app/ngspca/target/ngspca-0.01-SNAPSHOT.jar /app

COPY failed: stat app/ngspca/target/ngspca-0.01-SNAPSHOT.jar: file does not exist

**Comment by jlanej** [comment]
I [fixed](https://github.com/PankratzLab/NGS-PCA/commit/2ffbcfcb573be52b572fc2c96c51b212cf4e4976) the Docker file to COPY the ngspca-0.02-SNAPSHOT.jar that is actually being built by maven. If you pull the latest, let me know if the Dockerfile builds.

**Comment by davidroberson** [comment]
I pull your latest from git and it builds now.  Thank you!
